name: rust项目打包
on: push

permissions:
  contents: write
jobs:
  rust-build:
    name: cargo build工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 检查 cargo 版本 开始构建
        run: |
          cargo --version
          cargo build --release

      # - name: 上传构建产物
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release
      #     path: target/release/web-action

      - name: 分支部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./target/release/web-action
